### ISSUE TITLE
Fix the Player Name textarea

### ISSUE THREAD

**Issue by obstjn** [StarRealm/authority#1]
## Problem Statement
Adjust the styling of the Player Name textarea to resemble that of the original repository.

## Tasks
- [x] Have the textarea be a fixed size
- [x] Align text to center
- [x] Adjust font
- [x] Make text color white
- [ ] Disable line breaks in the textarea
  - [ ] Disable line break on desktop
  - [ ] Disable line break on mobile
  - [ ] Make "Enter" submit instead of line break
- [ ] (optional) adjust the area to the text length
